### PR TITLE
Init go modules

### LINKED ISSUE #31: Add go modules support
I can get this done

### PR DESCRIPTION
**Pull request by ferhatelmas**
Move to go modules with v2 and update readme and travis accordingly.

Bump supported go versions from go1.11 to latest.

Resolves #31.

### CODE REVIEW

**Comment by jfeliu007** [comment]
Thanks for the this PR. I didn't work on this yet because I am still green on the area of Go modules. Would you mind waiting a bit until I have the time to read more on go modules before we merge this one? There is a portion of the testing that is not being covered in this PR and I would like to see if we can remove the code or if we need to provide testing for that. :)

**Comment by ferhatelmas** [comment]
Sure, no worries. Take your time and anything else is needed, let me know.

**Comment by StacieClark** [comment]
What is the status of this?

**Comment by jfeliu007** [comment]
Failing tests. This might need to be redone. The test failed because the vendor folder was removed. We need to either change the test or include the vendor folders in the modules as part of the module package.

**Comment by ferhatelmas** [comment]
I can update it if you want to take it in.

**Comment by jfeliu007** [comment]
sure. master has quite a few changes since then. Make sure to take it into account. I would like to maintain the vendors' folder with `go mode vendors` and update the test if necessary. Thank you very much.

**Comment by ferhatelmas** [comment]
@jfeliu007 questions?

1. do you want to bump go versions from go 1.14 ? (IMHO why not)
2. do you want to keep testingsupport/vendor folder ? (IMHO no reason)

**Comment by jfeliu007** [comment]
> @jfeliu007 questions?
> 
> 1. do you want to bump go versions from go 1.14 ? (IMHO why not)
> 2. do you want to keep testingsupport/vendor folder ? (IMHO no reason)

1.- The lowest version necessary to support mods (I think it is 1.11, right)
2.- The purpose of the vendor folder in the testingsupport folder is to test that the library skips the vendors folder. There is a test for that. We either need to remove the test for the vendors folder or keep the vendors folder in the testingsupport folder. 

I am concerned now that automatic testing is not happening. Let me see if I can fix that before merging this.

**Comment by ferhatelmas** [comment]
@jfeliu007 Thanks for the details, I will address both.

**Comment by mariotoffia** [comment]
@jfeliu007 It would be super nice to have this PR going through! :)

**Comment by ferhatelmas** [comment]
@jfeliu007 address your comments and summary of changes:

* run in all go versions
* use mod=vendor for testing vendor
* add golangci for better module support and easier future extension of static analysis

Also, good to move to github actions IMHO, can take care of this next if you wish.

**Comment by mariotoffia** [comment]
@jfeliu007 Is there anything more needed in order to get @ferhatelmas PR merged?

Cheers,
 Mario :)

**Comment by icholy** [comment]
There is no reason to bump the version to v2.

**Comment by ferhatelmas** [comment]
going over open PRs from me without any updates and closing, so let me know if anything is needed from me.

**Pull request closed without merging**
